### ISSUE TITLE
Licence Request

### ISSUE THREAD

**Issue by pauldurrant** [mnezerka/dnslib#1]
This looks like just the library code I need for my current project. But I can't use it under GPL2 for the project I'm working on, as my project is for a proprietary product and I can't release its source code. Would you be willing to license your dnslib under a different licence, say the [Simplified BSD licence](https://en.wikipedia.org/wiki/BSD_licenses#2-clause)?

**Comment by mnezerka** [comment]
Hi, no problem. I'm open to any licence. But to tell the true, I'm not sure what exactly should I do to switch to Simplified BCD licence. If you tell me, I'll switch it.

**Comment by pauldurrant** [comment]
Many thanks. I have just looked at the licenses again, and it looks like the NCSA is the most modern version of the BSD license. See 

https://en.wikipedia.org/wiki/University_of_Illinois/NCSA_Open_Source_License
https://opensource.org/licenses/NCSA

Since I'm the one asking for the change, I've forked your repository and made a change request that includes all the needed changes to the licensing comments.

If you're happy with the changes, just merge the pull request into your repository. And many thanks.

**Comment by pauldurrant** [comment]
I'm very happy - thanks again. Issue closed.

**Comment by mnezerka** [comment]
Done. Enjoy my code. And feel free to push some changes. I don't use it anymore since I changed company and I'm out of telco business, where I used it for performance testing. But one never knows ....

**Comment by pauldurrant** [comment]
Dear Michal,

I can’t push changes at the moment, but I found one place that seemed to be missing a small amount of code.

In qs.h, lines 99,102 and 105 are missing the body of the functions. They should be
std::string getName() const { return mQName; };
uint getType() const { return mQType; };
eQClass getClass() const { return mQClass; };

(bold shows the additions)

Many thanks again for letting me use your code.

**Comment by mnezerka** [comment]
Hi. Thanks for info. Unfortunately, I'm not able to change anything by myself, since I'll not be able to run all tests even if it looks like code without impact on performance or memory allocation issues (I had lot of memory leaks).
